name: Sync to Aliyun
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: crpi-t1g420jmwip6fic.cn-beijing.personal.cr.aliyuncs.com
          username: nick4855555825
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
      - run: |
          docker pull nginx:latest
          docker tag nginx:latest crpi-t1g420jmwip6fic.cn-beijing.personal.cr.aliyuncs.com/ziyiwoaini/ziiyiwoaini-1:latest
          docker push crpi-t1g420jmwip6fic.cn-beijing.personal.cr.aliyuncs.com/ziyiwoaini/ziiyiwoaini-1:latest
